### ISSUE TITLE
Break client and api into separate services

### ISSUE THREAD

**Issue by switzerb** [folded-ear/foodinger#11]
Serve static assets separately from the api spring boot backend service

**Comment by barneyb** [comment]
Once the auth/api are on a different origin, the munging of the service worker can be removed from `package.json`'s postbuild

**Comment by barneyb** [comment]
All the nginx/routing BS would be _lovely_ to be able to test w/out doing production deploys. So I upvote! Via trendy git-based markdown mechanisms! By commenting!
