### ISSUE TITLE
Deleting recipe that's on the plan gives error message

### ISSUE THREAD

**Issue by switzerb** [folded-ear/foodinger#132]
{"timestamp":"2021-06-13T16:00:29.477+0000","status":500,"error":"Internal Server Error","message":"could not execute statement; SQL [n/a]; constraint [fk_task_ingredients_id]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement","path":"/api/recipe/376"}

There is a foreign key constraint on the task ingredients id that prevents the deletion of a recipe that is also present on a plan. We want to eliminate the constraint to allow deletion.

**Comment by barneyb** [comment]
As a recipe is deleted, the description is copied to any planned instances that don't already have customizations, and the link back to the recipe severed. No more FK violation.
